name: Note_App
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sqflite: any
  path_provider: any
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: fonts/Itim-Regular.ttf
    - family: RedHat
      fonts:
        - asset: fonts/RedHatText-Regular.ttf
        - asset: fonts/RedHatText-Bold.ttf
          weight: 700
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Regular.ttf
        - asset: fonts/Caveat-Bold.ttf
          weight: 700
    - family: Amaranth
      fonts:
        - asset: fonts/Amaranth-Regular.ttf